/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddLeave: typeof import('./pages/report/AddLeave.vue')['default']
    AddMember: typeof import('./pages/report/AddMember.vue')['default']
    AddProject: typeof import('./pages/report/AddProject.vue')['default']
    Auth: typeof import('./pages/authentication/Auth.vue')['default']
    BaseButton: typeof import('./components/bases/BaseButton.vue')['default']
    BaseCard: typeof import('./components/bases/BaseCard.vue')['default']
    BaseDatePicker: typeof import('./components/bases/BaseDatePicker.vue')['default']
    BaseField: typeof import('./components/bases/BaseField.vue')['default']
    BaseMultiselect: typeof import('./components/bases/BaseMultiselect.vue')['default']
    BaseTextField: typeof import('./components/bases/BaseTextField.vue')['default']
    BaseTitle: typeof import('./components/bases/BaseTitle.vue')['default']
    Dashboard: typeof import('./pages/layout/Dashboard.vue')['default']
    DashBoard: typeof import('./pages/report/DashBoard.vue')['default']
    Login: typeof import('./components/authentication/Login.vue')['default']
    MainContent: typeof import('./pages/layout/MainContent.vue')['default']
    MemberFine: typeof import('./pages/report/MemberFine.vue')['default']
    MemberLeave: typeof import('./pages/report/MemberLeave.vue')['default']
    MemberList: typeof import('./pages/reporting-system/MemberList.vue')['default']
    MemberReport: typeof import('./pages/report/MemberReport.vue')['default']
    MenPower: typeof import('./pages/report/MenPower.vue')['default']
    ParentCard: typeof import('./components/card/ParentCard.vue')['default']
    Profile: typeof import('./pages/authentication/Profile.vue')['default']
    ProfileIcon: typeof import('./components/navbar/ProfileIcon.vue')['default']
    ReportingPage: typeof import('./pages/reporting-system/ReportingPage.vue')['default']
    ReportPage: typeof import('./pages/report/ReportPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowProject: typeof import('./pages/report/ShowProject.vue')['default']
    SideBar: typeof import('./components/sidebar/SideBar.vue')['default']
    TableCard: typeof import('./components/card/TableCard.vue')['default']
    TopNavbar: typeof import('./pages/layout/TopNavbar.vue')['default']
    WidgetCard: typeof import('./components/card/WidgetCard.vue')['default']
    WorkingTime: typeof import('./pages/report/WorkingTime.vue')['default']
  }
}
