/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./pages/report/404.vue')['default']
    AddLeave: typeof import('./pages/report/AddLeave.vue')['default']
    AddMember: typeof import('./pages/report/AddMember.vue')['default']
    AddProject: typeof import('./pages/report/AddProject.vue')['default']
    AddSkill: typeof import('./pages/report/AddSkill.vue')['default']
    Auth: typeof import('./pages/authentication/Auth.vue')['default']
    BaseAutoComplete: typeof import('./components/bases/BaseAutoComplete.vue')['default']
    BaseButton: typeof import('./components/bases/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./components/bases/BaseCheckbox.vue')['default']
    BaseConfirmDelete: typeof import('./components/bases/BaseConfirmDelete.vue')['default']
    BaseDatePicker: typeof import('./components/bases/BaseDatePicker.vue')['default']
    BaseFileInput: typeof import('./components/bases/BaseFileInput.vue')['default']
    BaseMultiSelect: typeof import('./components/bases/BaseMultiSelect.vue')['default']
    BaseSelect: typeof import('./components/bases/BaseSelect.vue')['default']
    BaseTable: typeof import('./components/bases/BaseTable.vue')['default']
    BaseTextField: typeof import('./components/bases/BaseTextField.vue')['default']
    BaseTitle: typeof import('./components/bases/BaseTitle.vue')['default']
    CroppieWrapper: typeof import('./components/croppie/CroppieWrapper.vue')['default']
    Dashboard: typeof import('./pages/layout/Dashboard.vue')['default']
    DashBoard: typeof import('./pages/report/DashBoard.vue')['default']
    LeaveRecord: typeof import('./pages/reporting-system/LeaveRecord.vue')['default']
    Login: typeof import('./components/authentication/Login.vue')['default']
    MainContent: typeof import('./pages/layout/MainContent.vue')['default']
    MemberFine: typeof import('./pages/report/MemberFine.vue')['default']
    MemberLeave: typeof import('./pages/report/MemberLeave.vue')['default']
    MemberList: typeof import('./pages/reporting-system/MemberList.vue')['default']
    MemberReport: typeof import('./pages/report/MemberReport.vue')['default']
    MemeberSkill: typeof import('./pages/report/MemeberSkill.vue')['default']
    MenPower: typeof import('./pages/report/MenPower.vue')['default']
    ParentCard: typeof import('./components/card/ParentCard.vue')['default']
    Profile: typeof import('./pages/authentication/Profile.vue')['default']
    ProfileIcon: typeof import('./components/navbar/ProfileIcon.vue')['default']
    ReportingPage: typeof import('./pages/reporting-system/ReportingPage.vue')['default']
    ReportPage: typeof import('./pages/report/ReportPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingBar: typeof import('./components/sidebar/SettingBar.vue')['default']
    ShowProject: typeof import('./pages/report/ShowProject.vue')['default']
    SideBar: typeof import('./components/sidebar/SideBar.vue')['default']
    StaffCard: typeof import('./pages/report/StaffCard.vue')['default']
    StaffCardCanvas: typeof import('./components/report/StaffCardCanvas.vue')['default']
    TopNavbar: typeof import('./pages/layout/TopNavbar.vue')['default']
    WidgetCard: typeof import('./components/card/WidgetCard.vue')['default']
    WorkingTime: typeof import('./pages/report/WorkingTime.vue')['default']
  }
}
