/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMember: typeof import('./pages/report/AddMember.vue')['default']
    Auth: typeof import('./pages/authentication/Auth.vue')['default']
    BaseButton: typeof import('./components/bases/BaseButton.vue')['default']
    BaseCard: typeof import('./components/bases/BaseCard.vue')['default']
    BaseDatePicker: typeof import('./components/bases/BaseDatePicker.vue')['default']
    BaseTitle: typeof import('./components/bases/BaseTitle.vue')['default']
    Dashboard: typeof import('./pages/layout/Dashboard.vue')['default']
    DashBoard: typeof import('./pages/report/DashBoard.vue')['default']
    DashboardLayout: typeof import('./pages/layout/DashboardLayout.vue')['default']
    HomePage: typeof import('./pages/HomePage.vue')['default']
    Log: typeof import('./components/authentication/log.vue')['default']
    Login: typeof import('./components/authentication/Login.vue')['default']
    MainContent: typeof import('./pages/layout/MainContent.vue')['default']
    Pages: typeof import('./pages/index.vue')['default']
    ReportingPage: typeof import('./pages/reporting-system/ReportingPage.vue')['default']
    ReportPage: typeof import('./pages/report/ReportPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/sidebar/SideBar.vue')['default']
    TopNavbar: typeof import('./pages/layout/TopNavbar.vue')['default']
  }
}
